# For more configuration options visit https://docs.codeclimate.com/docs/advanced-configuration

version: "2"
plugins:
  # https://www.sonarsource.com/products/codeanalyzers/sonarjava.html
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "8"
  # http://checkstyle.sourceforge.net/config.html
  checkstyle:
    enabled: true
    config:
      file: ".checkstyle.xml"