# For more configuration options visit https://docs.codeclimate.com/docs/advanced-configuration

version: "2"
prepare:
  fetch:
    - url: "https://raw.githubusercontent.com/checkstyle/checkstyle/checkstyle-8.18/src/main/resources/google_checks.xml"
      path: ".checkstyle.xml"
plugins:
  # https://www.sonarsource.com/products/codeanalyzers/sonarjava.html
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "8"
  # http://checkstyle.sourceforge.net/config.html
  checkstyle:
    enabled: true
    config:
      file: ".checkstyle.xml"